@startuml

actor Painter as P

note over P #AliceBlue: AliceBlue
note over P #AntiqueWhite: AntiqueWhite
note over P #Aqua: Aqua
note over P #Aquamarine: Aquamarine
note over P #Azure: Azure
note over P #Beige: Beige
note over P #Bisque: Bisque
note over P #Black: Black
note over P #BlanchedAlmond: BlanchedAlmond
note over P #Blue: Blue
note over P #BlueViolet: BlueViolet
note over P #Brown: Brown
note over P #BurlyWood: BurlyWood
note over P #CadetBlue: CadetBlue
note over P #Chartreuse: Chartreuse
note over P #Chocolate: Chocolate
note over P #Coral: Coral
note over P #CornflowerBlue: CornflowerBlue
note over P #Cornsilk: Cornsilk
note over P #Crimson: Crimson
note over P #Cyan: Cyan
note over P #DarkBlue: DarkBlue
note over P #DarkCyan: DarkCyan
note over P #DarkGoldenRod: DarkGoldenRod
note over P #DarkGray: DarkGray
note over P #DarkGreen: DarkGreen
note over P #DarkGrey: DarkGrey
note over P #DarkKhaki: DarkKhaki
note over P #DarkMagenta: DarkMagenta
note over P #DarkOliveGreen: DarkOliveGreen
note over P #DarkOrchid: DarkOrchid
note over P #DarkRed: DarkRed
note over P #DarkSalmon: DarkSalmon
note over P #DarkSeaGreen: DarkSeaGreen
note over P #DarkSlateBlue: DarkSlateBlue
note over P #DarkSlateGray: DarkSlateGray
note over P #DarkSlateGrey: DarkSlateGrey
note over P #DarkTurquoise: DarkTurquoise
note over P #DarkViolet: DarkViolet
note over P #Darkorange: Darkorange
note over P #DeepPink: DeepPink
note over P #DeepSkyBlue: DeepSkyBlue
note over P #DimGray: DimGray
note over P #DimGrey: DimGrey
note over P #DodgerBlue: DodgerBlue
note over P #FireBrick: FireBrick
note over P #FloralWhite: FloralWhite
note over P #ForestGreen: ForestGreen
note over P #Fuchsia: Fuchsia
note over P #Gainsboro: Gainsboro
note over P #GhostWhite: GhostWhite
note over P #Gold: Gold
note over P #GoldenRod: GoldenRod
note over P #Gray: Gray
note over P #Green: Green
note over P #GreenYellow: GreenYellow
note over P #Grey: Grey
note over P #HoneyDew: HoneyDew
note over P #HotPink: HotPink
note over P #IndianRed: IndianRed
note over P #Indigo: Indigo
note over P #Ivory: Ivory
note over P #Khaki: Khaki
note over P #Lavender: Lavender
note over P #LavenderBlush: LavenderBlush
note over P #LawnGreen: LawnGreen
note over P #LemonChiffon: LemonChiffon
note over P #LightBlue: LightBlue
note over P #LightCoral: LightCoral
note over P #LightCyan: LightCyan
note over P #LightGoldenRodYellow: LightGoldenRodYellow
note over P #LightGray: LightGray
note over P #LightGreen: LightGreen
note over P #LightGrey: LightGrey
note over P #LightPink: LightPink
note over P #LightSalmon: LightSalmon
note over P #LightSeaGreen: LightSeaGreen
note over P #LightSkyBlue: LightSkyBlue
note over P #LightSlateGray: LightSlateGray
note over P #LightSlateGrey: LightSlateGrey
note over P #LightSteelBlue: LightSteelBlue
note over P #LightYellow: LightYellow
note over P #Lime: Lime
note over P #LimeGreen: LimeGreen
note over P #Linen: Linen
note over P #Magenta: Magenta
note over P #Maroon: Maroon
note over P #MediumAquaMarine: MediumAquaMarine
note over P #MediumBlue: MediumBlue
note over P #MediumOrchid: MediumOrchid
note over P #MediumPurple: MediumPurple
note over P #MediumSeaGreen: MediumSeaGreen
note over P #MediumSlateBlue: MediumSlateBlue
note over P #MediumSpringGreen: MediumSpringGreen
note over P #MediumTurquoise: MediumTurquoise
note over P #MediumVioletRed: MediumVioletRed
note over P #MidnightBlue: MidnightBlue
note over P #MintCream: MintCream
note over P #MistyRose: MistyRose
note over P #Moccasin: Moccasin
note over P #NavajoWhite: NavajoWhite
note over P #Navy: Navy
note over P #OldLace: OldLace
note over P #Olive: Olive
note over P #OliveDrab: OliveDrab
note over P #Orange: Orange
note over P #OrangeRed: OrangeRed
note over P #Orchid: Orchid
note over P #PaleGoldenRod: PaleGoldenRod
note over P #PaleGreen: PaleGreen
note over P #PaleTurquoise: PaleTurquoise
note over P #PaleVioletRed: PaleVioletRed
note over P #PapayaWhip: PapayaWhip
note over P #PeachPuff: PeachPuff
note over P #Peru: Peru
note over P #Pink: Pink
note over P #Plum: Plum
note over P #PowderBlue: PowderBlue
note over P #Purple: Purple
note over P #Red: Red
note over P #RosyBrown: RosyBrown
note over P #RoyalBlue: RoyalBlue
note over P #SaddleBrown: SaddleBrown
note over P #Salmon: Salmon
note over P #SandyBrown: SandyBrown
note over P #SeaGreen: SeaGreen
note over P #SeaShell: SeaShell
note over P #Sienna: Sienna
note over P #Silver: Silver
note over P #SkyBlue: SkyBlue
note over P #SlateBlue: SlateBlue
note over P #SlateGray: SlateGray
note over P #SlateGrey: SlateGrey
note over P #Snow: Snow
note over P #SpringGreen: SpringGreen
note over P #SteelBlue: SteelBlue
note over P #Tan: Tan
note over P #Teal: Teal
note over P #Thistle: Thistle
note over P #Tomato: Tomato
note over P #Turquoise: Turquoise
note over P #Violet: Violet
note over P #Wheat: Wheat
note over P #White: White
note over P #WhiteSmoke: WhiteSmoke
note over P #Yellow: Yellow
note over P #YellowGreen: YellowGreen
@enduml
